### ISSUE TITLE
clear input after click

### ISSUE THREAD

**Issue by pixelomedia** [running-coder/jquery-typeahead#93]
Hi, I want to clear input after select from hint list. Nothing like .val() is working. Is there some solution?

Thanks

**Comment by running-coder** [comment]
Hey, have you tried

``` javascript
callback: {
        onClickAfter: function (node, a, item, event) {
            node.val('');
        }
}
```

**Comment by pixelomedia** [comment]
Thank you so much for quickly support! This one working pretty well, I didn't found it in documentation or support. Cheers

**Comment by pixelomedia** [comment]
Sorry. I think everything is fine - but not. This one is doing same problem like I trying with remove some of your code. First searching si working. But every next search is return TypeError: this.xhr[i].abort is not a function this.xhr[i].abort(); in console

**Comment by running-coder** [comment]
I was able to reproduce the error with jquery 2.1.x while it's working fine on 1.11.x, perhaps the .abort() behavior was changed. Anyway I've added a small fix to clear the request from memory once they are completed.

**Comment by pixelomedia** [comment]
Amazing support! Yes, I used jquery 2.1. Now everything working perfectly. Thank you
